### ISSUE TITLE
ValueError: Cannot found kpoint [ 0.5 -0.5  0. ] in PROCAR files

### ISSUE THREAD

**Issue by khaledb9** [SMTG-Bham/easyunfold#31]
Hello. 

I did a bandunfolding with the split option into 7 calculations. The overall bandstructure is plotted but the plotting projections yields the error: 

ValueError: Cannot found kpoint [ 0.5 -0.5  0. ] in PROCAR files

Strangely, the output of grep gives in the last procar file: 
 k-point     9 :    0.50000000 -0.50000000 0.00000000     weight = 0.11111111

The point is there in the file but the program cannot find it.

**Comment by zhubonan** [comment]
Thanks for reporting the issue. Please more information about the error. I am afraid without such information it is impossible to know what causes the issue... Also, what code version are you using?

**Comment by kavanase** [comment]
@khaledb9 this error should be fixed with the updated code from #32 (as @zhubonan mentioned in #30). 
Can you please let us know if the updated code works for you now, or if you're still having issues? 
Thanks!

**Comment by khaledb9** [comment]
Hi
Sorry for the delayed response. The issue is solved and it was related to the handling of spin. Thanks !
