### ISSUE TITLE
Documentation does not specify how to run tests

### ISSUE THREAD

**Issue by srmnitc** [SMTG-Bham/easyunfold#35]
This is part of review for JOSS over at https://github.com/openjournals/joss-reviews/issues/5974

There are automated tests within the repository, which is great! However it is not explained in the documentation how to install the dependencies for the tests, or how to run the tests themselves manually. Adding a small section explaining this could be quite useful.

**Comment by zhubonan** [comment]
Thanks, instructions have been added to the docs, along with some notes about development:

https://github.com/SMTG-Bham/easyunfold/blob/1ae2b7546e74d9656fee82ae20a759c5ad84d64c/docs/index.md?plain=1#L123C10-L140
