### ISSUE TITLE
Does this package support `Band re-ordering`?

### ISSUE THREAD

**Issue by hongyi-zhao** [SMTG-Bham/easyunfold#46]
I'm not sure if this package also supports the feature `Band re-ordering` as the one implemented in [VaspBandUnfolding](https://github.com/QijingZheng/VaspBandUnfolding#band-re-ordering):

![image](https://github.com/SMTG-Bham/easyunfold/assets/11155854/8fd4fd52-cd91-42ca-98aa-577db38ddd9e)

Regards,
Zhao

**Comment by kavanase** [comment]
Hi @hongyi-zhao, band re-ordering is not supported in `easyunfold`, as this is related to normal band structure plots and not unfolded band structures. For unfolded band structures we do not have the same band index labelling as for normal primitive cell band structures, so band re-ordering does not make sense here in the same way it does for primitive cell bandstructures, which is the use case in `VaspBandUnfolding`. Hope that answers your question!
