### ISSUE TITLE
export to gnuplot data format

### ISSUE THREAD

**Issue by nityasagarjena** [SMTG-Bham/easyunfold#47]
Is it possible to export the energy, k, spectral weight to gnuplot unfold.dat format, likewise we have for sumo (energy vs k) as band.dat?

**Comment by kavanase** [comment]
Hi @nityasagarjena,
Yes this is possible through the python API, with the `UnfoldKSet.get_spectral_function()` and `UnfoldKSet.get_spectral_weights()` functions, and you can see how these are used in `easyunfold.cli` and `easyunfold.plotting`. But it is not automated via CLI like `sumo` – I'm not sure if @zhubonan plans to add this in the future
