### ISSUE TITLE
There are flat bands in unfolded band structure of supercell structure (K-paths are not recognized well)

### ISSUE THREAD

**Issue by Douwz** [SMTG-Bham/easyunfold#49]
I calculated the unfolded band structure of Sb2Si2Te6 supercell with pymatgen k-path.  There are some flat bands between high symmetry points when I plot the unfolded band structure without atom projections, but the unfolded band structure becomes normal when I plot it with atom projections.
![band](https://github.com/SMTG-Bham/easyunfold/assets/66117552/af95c827-d7a5-4d9d-9286-9ff031e704d9)

**Comment by zhubonan** [comment]
Seems like some kind of bug to me... Could you please provide the .json file containing the spectral weights?

**Comment by Douwz** [comment]
Yeah. 
[easyunfold.json](https://github.com/SMTG-Bham/easyunfold/files/15021347/easyunfold.json)

**Comment by zhubonan** [comment]
Resolved via #51
