### ISSUE TITLE
Initial feedback - hybrid folders

### ISSUE THREAD

**Issue by joebesity** [SMTG-Bham/easyunfold#5]
Hi Bonan, so far the package is behaving well, I'm road-testing some ZnO supercells. One thing that I've noticed that would be a nice quality of life update is to have something similar to the folder generation in sumo. Currently, if you have say 8 splits for the band structure, it makes the 8 KPOINTS files, but then you have to manually sort out 8 separate calcs. In sumo the `-f` option pastes KPOINTS splits and relevant input files into fresh directories. This would be a nice feature :)

Will keep you updated if I find anything else, and will let you know how the calcs go. Cheers, Joe

**Comment by zhubonan** [comment]
This has been implemented as:

```
easyunfold generate --nk-per-split <n> --scf-kpoints <IBZKPT-file>
```

and to use multiple WAVECAR files:

```
easyunfold calculation <WAVECAR1> <WAVECAR2> ....
```

**Comment by zhubonan** [comment]
I just realised that the comment is about making folders that are ready for calculations. Reopened the issue to track.

**Comment by kavanase** [comment]
@zhubonan is the plan to implement the folder making as a code feature or just leave as is (split kpoints generation, but then up to the user to setup and run the calculations for these)?
Just some housekeeping!

**Comment by zhubonan** [comment]
Close via #44
